name: deploy

on:
  workflow_dispatch:
    inputs:
      tags: 
         description: 'Run Tags'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: deploy new docker image
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST1 }}:${{ secrets.PORT }}"
          sync: true
          command_timeout: "10m"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            screen -dm bash -c "./autoupdate.sh ; exec bash"
