name: ci

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tags: 
         description: 'Run Tags'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: morzlee/l4d2:latest
      -
        name: deploy new docker image to all server
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST1 }}:${{ secrets.PORT }},106.55.6.211,106.13.221.250,124.221.215.53,124.221.10.99"
          sync: true
          command_timeout: "10m"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            screen -dm bash -c "./autoupdate.sh ; exec bash"
