name: dockeronly

on:
  workflow_dispatch:
    inputs:
      tags: 
         description: 'Run Tags'
  push:
    branches:
      - build


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 刷新NEEDUPDATE变量，以放弃update阶段缓存
        run: echo "NEEDUPDATE=$( date +%s )" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: morzlee/l4d2:latest
          cache-from: type=registry,ref=morzlee/l4d2:buildcache
          cache-to: type=registry,ref=morzlee/l4d2:buildcache,mode=max,compression=zstd
          build-args: |
            NEEDUPDATE=${{ env.NEEDUPDATE }}
